### ISSUE TITLE
the daily builds seem to be stuck with an old date?

### ISSUE THREAD

**Issue by Jay-Jay-OPL** [AKuHAK/test_build#3]
I want to know if the auto-script you created stopped working?

https://akuhak.github.io/test_build/

It seems to show a very old date: **2018-04-16**

Plus, do you know if any of the new changes made to PS2SDK or PS2ETH recently broke OPL from running?

I had to revert back to an older PS2SDK commit to be able to compile OPL.

Yesterday, I purchased a new PC, and installed ps2toolchain, and had this issue, until I was able to revert back to an older version of PS2SDK.

**Comment by AKuHAK** [comment]
Yeah i know about broken builds - unfortunately - I dont have time to fix it until Friday. As about broken OPL - I didnt know about ps2sdk changes which broke it.

**Comment by AKuHAK** [comment]
It seems that problem fixed...

**Comment by Jay-Jay-OPL** [comment]
Can you also verify if the PS2SDK is good to update?  The last working commit for me for PS2SDK on a **Windows Compiling** environment is:  d5ce63a (Feb 25, 2018 )

But then I am not sure if it's a PS2SDK problem or the other updates like ps2eth, gsKit or ps2toolchain, since when I installed it on a new PC, I had to install all that.

Also, I sent you a PM at PS2-HOME about a possible bug in wLE.

**Comment by Jay-Jay-OPL** [comment]
Sorry for my double-post, I just discovered that both OPL and wLE compiles display the same commit value on this page:  https://akuhak.github.io/test_build/

The "possible" wLE bug that I've mentioned above is being discussed here in this topic: http://www.ps2-home.com/forum/viewtopic.php?f=16&t=5493
