### ISSUE TITLE
The Auto BOT seems to be broken?

### ISSUE THREAD

**Issue by Jay-Jay-OPL** [AKuHAK/test_build#5]
Whenever I attempt to download either wLE or OPL, I get a **404 Error** message.

Unless there is a new URL?  Let me know?

Testing: https://akuhak.github.io/test_build/

**Comment by AKuHAK** [comment]
Oh shi... really broken - I will look at it asap

**Comment by AKuHAK** [comment]
Should be fixed now

**Comment by mahoneyt944** [comment]
Just tried to run the boot.elf , it freezes the console after a few seconds. I redownloaded, tried again, same thing. Might still be an issue? 

Reverted back to 1/14 build and freezing fixed.
