### ISSUE TITLE
boot.elf , freezes the console after a few seconds.

### ISSUE THREAD

**Issue by mahoneyt944** [AKuHAK/test_build#6]
Just tried to run the boot.elf , it freezes the console after a few seconds. I redownloaded, tried again, same thing. Might still be an issue with the auto bot/ compile? 

Reverted back to 1/14 build and freezing fixed.

_Originally posted by @mahoneyt944 in https://github.com/AKuHAK/test_build/issues/5#issuecomment-599306169_

**Comment by AKuHAK** [comment]
please post this issue in ulaunchelf repository
